apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mxjjd53lw-python
  janus-idp.io/tekton: mxjjd53lw-python
  backstage.io/kubernetes-id: mxjjd53lw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mxjjd53lw-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
